pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/NicolitoG/TingesoLab1']])
                dir("front-end-1"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("front-end-1"){
                    script{
                        withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build --no-cache -t nicolitog/imagenfrontend:latest ."
                            bat "docker push nicolitog/imagenfrontend:latest"
                        }
                    }
                }
            }
        }
    }
}